version: 2.1

jobs:
  buildkernel:

    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run: export TELEGRAM_TOKEN="$TELE_TOKEN"
      - run: export TELEGRAM_CHAT="$TELE_CHAT"
      - run: export GITHUB_TOKEN="$OTH_TOKEN"
      - run: export release_repo="B4gol/kernelscript"
      - run: export zip_name="NWkernel-Riva-"$(env TZ='Asia/Jakarta' date +%Y%m%d)""
      - run:  sudo apt-get update && sudo apt install -y liblz4-dev openjdk-8-jdk android-tools-adb bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev
      - run: cd $HOME && PATH=~/bin:$PATH
      - run: curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            - chmod a+x ~/bin/repo
      - run: cd $HOME && git clone https://github.com/B4gol/kernelscript.git buildkernel
      - run: chmod a+x $HOME/buildkernel/telegram
      - run: SYNC_START=$(date +"%s")
      - run: $HOME/buildkernel/telegram -M "Sync Started"
      - run: cd $HOME && git clone -b 11-master https://github.com/B4gol/platform-kernelist-xiaomi-rova.git --depth 1 kernel
      - run: cp $HOME/buildkernel/build.sh $HOME/kernel/build.sh
      - run: cd $HOME/kernel && chmod +x build.sh
      - run: SYNC_END=$(date +"%s")
      - run: SYNC_DIFF=$((SYNC_END - SYNC_START))
      - run: $HOME/buildkernel/telegram -M "Sync completed successfully in $((SYNC_DIFF / 60)) minute(s) and $((SYNC_DIFF % 60)) seconds"
      - run: BUILD_START=$(date +"%s")
      - run: cd $HOME/kernel
      - run: source build.sh
      - run: make -j4 O=out
      - run: cp $HOME/buildkernel/strip.sh $HOME/kernel/strip.sh
      - run: cp $HOME/buildkernel/c.sh $HOME/kernel/c.sh
      - run: git config --global user.name "B4gol"
      - git config --global user.email "ivansuselo@gmail.com"
      - run: git tag $CIRCLECI_TAG
      - run: cd $HOME/kernel && chmod +x strip.sh && source strip.sh
      - run: cd $HOME/kernel && chmod +x c.sh && source c.sh
            # Set up git user name and tag this commit
workflows:
  build_workflow:
    jobs:
      - docker
