version: 2.1
jobs:
  linux:
    machine:
      - image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:  echo "Environment Setup"
              TELEGRAM_TOKEN=$TELE_TOKEN
              TELEGRAM_CHAT=$TELE_CHAT
              GITHUB_TOKEN=$OTH_TOKEN
              CIRCLECI_TAG=$CIRCLECI_TAG
      - run:  wget https://gist.githubusercontent.com/B4gol/f9b42daf26b8be1ecb4f314c40c82fdc/raw/kernit.dev -O - | sh
workflows:
  linux-workflow:
    jobs:
      - linux
