version: 2.1

jobs:
  decent:

    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:  echo "Environment Setup"
              TELEGRAM_TOKEN=$TELE_TOKEN
              TELEGRAM_CHAT=$TELE_CHAT
              GITHUB_TOKEN=$OTH_TOKEN
              tag=$CIRCLECI_TAG
      - run:  wget https://gist.githubusercontent.com/B4gol/8d9a629272cdf3084f455f651dea7483/raw/setup.sh && chmod +x setup.sh && sudo bash setup.sh
workflows:
  decent-workflow:
    jobs:
      - decent
