version: 2.1

jobs:
  decent:

    docker:
      - image: cimg/base:stable

    steps:
      - run:
          # before_install:
            - export TELEGRAM_TOKEN="$TELE_TOKEN"
            - export TELEGRAM_CHAT="$TELE_CHAT"
            - export GITHUB_TOKEN="$OTH_TOKEN"
            - export release_repo="B4gol/kernelscript2"
            - export zip_name="NWkernel-Riva-"$(env TZ='Asia/Jakarta' date +%Y%m%d)""
            - sudo apt-get update
            - sudo apt install -y liblz4-dev openjdk-8-jdk android-tools-adb bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev
          # before_script:
            - cd $HOME && PATH=~/bin:$PATH
            - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            - chmod a+x ~/bin/repo
          # script:
            - cd $HOME && git clone https://github.com/B4gol/kernelscript.git buildkernel
            - chmod a+x $HOME/buildkernel/telegram
            - SYNC_START=$(date +"%s")
            - $HOME/buildkernel/telegram -M "Sync Started"
            - cd $HOME && git clone -b 11-master https://github.com/B4gol/platform-kernelist-xiaomi-rova.git --depth 1 kernel
            - cp $HOME/buildkernel/build.sh $HOME/kernel/build.sh
            - cd $HOME/kernel && chmod +x build.sh
            - SYNC_END=$(date +"%s")
            - SYNC_DIFF=$((SYNC_END - SYNC_START))
            - $HOME/buildkernel/telegram -M "Sync completed successfully in $((SYNC_DIFF / 60)) minute(s) and $((SYNC_DIFF % 60)) seconds"
            - BUILD_START=$(date +"%s")
            - cd $HOME/kernel
            - source build.sh
            - make -j4 O=out
            - cp $HOME/buildkernel/strip.sh $HOME/kernel/strip.sh
            - cp $HOME/buildkernel/c.sh $HOME/kernel/c.sh
            - git config --local user.name "B4gol"
            - git config --local user.email "randomidn6@gmail.com"
            - git tag $CIRCLECI_TAG
            - cd $HOME/kernel && chmod +x strip.sh && source strip.sh
            - cd $HOME/kernel && chmod +x c.sh && source c.sh
          # before_deploy:
            # Set up git user name and tag this commit
          deploy:
            provider: releases
            api_key: "$OTH_TOKEN"
            file: $HOME/buildkernel/AnyKernel/$zip_name.zip
            skip_cleanup: true
          on:
            tags: true
            repo: B4gol/kernelscript
            branch: newline


workflows:
  version: 2.1
    decent_build:
      jobs
        - docker
