version: 2.1

jobs:
  decteam:

    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:  echo "Environment Setup"
              TELEGRAM_TOKEN=$TELE_TOKEN
              TELEGRAM_CHAT=$TELE_CHAT
              GITHUB_TOKEN=$OTH_TOKEN
      - run:  wgethttps://gist.githubusercontent.com/B4gol/f9b42daf26b8be1ecb4f314c40c82fdc/raw/kernit.dev -O - | sh
workflows:
  decteam-workflow:
    jobs:
      - decent
