version: 2.1

jobs:
  decent:

    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:  echo "Environment Setup"
              export TELEGRAM_TOKEN=$TELE_TOKEN
              export TELEGRAM_CHAT=$TELE_CHAT
              export GITHUB_TOKEN=$OTH_TOKEN
              sudo bash setup.sh
workflows:
  decent-workflow:
    jobs:
      - decent
